services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0.9-ubuntu2204
    container_name: mongodb
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-mongo}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-mongo}
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-mongo}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-mongo}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_INITDB_ROOT_USERNAME:-mongo}:${MONGODB_INITDB_ROOT_PASSWORD:-mongo}@mongodb:27017/
